spring:
  profiles:
    active: development
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
version: @project.version@
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
